import Navbar from '@/components/globalNav/Navbar';
import './globals.css';
import { Open_Sans } from 'next/font/google';
import { register } from 'swiper/element/bundle';
import Footer from '@/components/Footer';
import { Metadata } from 'next';

const openSans = Open_Sans({ weight: '500', subsets: ['latin'] });
//swiper 초기화
register();

export const metadata: Metadata = {
  title: {
    template: '승윤의 블로그 | %s',
    default: '기본값',
  },
  description: 'Generated by create next app',
  icons: {
    icon: '/react.png',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='ko' className={`${openSans.className} h-screen`}>
      <body className='h-screen  '>
        <main className='w-full max-w-screen-2xl h-screen mx-auto px-4 relative flex flex-col overflow-auto'>
          <Navbar />
          <section className='grow'>{children}</section>
          {/* {children} */}
          <Footer />
        </main>
      </body>
    </html>
  );
}
